# Generated by Django 5.1.2 on 2024-10-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.DecimalField(decimal_places=0, max_digits=8, null=True),
        ),
    ]
