# Generated by Django 5.1.2 on 2024-10-29 23:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_alter_batch_left_alter_product_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="number",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="record_date",
        ),
        migrations.RemoveField(
            model_name="saleitem",
            name="sale_number",
        ),
        migrations.AddField(
            model_name="sale",
            name="timestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="transaction_id",
            field=models.DecimalField(
                decimal_places=0, max_digits=50, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="sale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="dashboard.sale",
                null=True,
            ),
            preserve_default=False,
        ),
    ]
