# Generated by Django 5.1.2 on 2024-10-29 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_remove_sale_number_remove_sale_record_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="saleitem",
            name="sale",
        ),
        migrations.RemoveField(
            model_name="saleitem",
            name="product",
        ),
        migrations.DeleteModel(
            name="Sale",
        ),
        migrations.DeleteModel(
            name="SaleItem",
        ),
    ]
