# Generated by Django 5.1.2 on 2024-10-30 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0010_sale_saleitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="saleitem",
            name="product",
        ),
        migrations.AddField(
            model_name="saleitem",
            name="product_code",
            field=models.DecimalField(
                decimal_places=0, max_digits=8, null=True, unique=True
            ),
        ),
    ]
