# Generated by Django 5.1.2 on 2024-10-30 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0011_remove_saleitem_product_saleitem_product_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="saleitem",
            name="sale",
        ),
        migrations.DeleteModel(
            name="Sale",
        ),
        migrations.DeleteModel(
            name="SaleItem",
        ),
    ]
