# Generated by Django 5.1.2 on 2024-11-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0015_saleitem_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="last_expired_products_check",
            field=models.DateField(null=True),
        ),
    ]
