# Generated by Django 5.1.2 on 2024-11-01 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0016_product_last_expired_products_check"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="last_expired_products_check",
            field=models.DateField(default=None, null=True),
        ),
    ]
