# Generated by Django 5.1.2 on 2024-11-01 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0017_alter_product_last_expired_products_check"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="last_expired_products_check",
        ),
    ]
