# Generated by Django 5.1.2 on 2024-11-02 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0018_remove_product_last_expired_products_check"),
    ]

    operations = [
        migrations.CreateModel(
            name="WritenOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_date", models.DateTimeField(auto_now_add=True)),
                ("quantity", models.IntegerField(default=0, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.batch",
                    ),
                ),
            ],
        ),
    ]
