# Generated by Django 5.1.2 on 2024-11-03 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0019_writenoff"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_range_start", models.DateField()),
                ("date_range_end", models.DateField()),
                ("sales_count", models.PositiveIntegerField(default=0)),
                ("written_off_count", models.PositiveIntegerField(default=0)),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "loss",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="dashboard.product",
                    ),
                ),
            ],
        ),
    ]
