# Generated by Django 5.1.2 on 2024-11-03 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0020_itemreport"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ItemReport",
        ),
    ]
