# Generated by Django 5.1.2 on 2024-11-11 08:36

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0021_delete_itemreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="record_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="product",
            name="code",
            field=models.CharField(
                max_length=8,
                null=True,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(8)],
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="transaction_id",
            field=models.CharField(
                max_length=10,
                null=True,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="saleitem",
            name="product_code",
            field=models.CharField(
                max_length=8,
                null=True,
                validators=[django.core.validators.MinLengthValidator(8)],
            ),
        ),
    ]
