# Generated by Django 5.1.2 on 2024-11-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0023_alter_writenoff_record_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="record_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="writenoff",
            name="record_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
